name: GraalVM Native Image builds
on: [push, pull_request]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  image-generation:
    name: Test
    runs-on: windows-latest

    steps:
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - if: runner.os == 'Windows'
        run: native-image -Djava.home="$env:GRAALVM_HOME" --version

      - name: boostrap
        run: mkdir tmp && cat ${GRAALVM_HOME}/bin/native-image.cmd
        #&& ln -s ${GRAALVM_HOME}/bin/native-image.cmd ${GRAALVM_HOME}/bin/native-image
        shell: bash

      - name: Build and run HelloWorld.java
        run: |
          echo 'public class HelloWorld { public static void main(String[] args) { System.out.println("Hello, World!"); } }' > HelloWorld.java
          javac HelloWorld.java
          ${GRAALVM_HOME}/bin/native-image.cmd -Djava.home="${GRAALVM_HOME}" HelloWorld ./tmp/helloworld
          ./tmp/helloworld
        shell: bash

      - name: compress tools
        run: 7z
        shell: bash

      - name: bash test
        run: mkdir -p xpto/x && ls -lha ./xpto/x
        shell: bash

#  uname -mo
#      x86_64 Msys
#      - name: aa
#        run: ln -s $GRAALVM_HOME/native-image.cmd $GRAALVM_HOME/native-image
#        shell: bash
#      - name: b
#        run: $GRAALVM_HOME/bin/native-image --version
#        run: ls -lha $GRAALVM_HOME/bin
#        shell: bash
