name: GraalVM Native Image builds
on: [push, pull_request]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  image-generation:
    name: Test
    runs-on: windows-latest

    steps:
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - if: runner.os == 'Windows'
        run: ln -s $GRAALVM_HOME/native-image.cmd $GRAALVM_HOME/native-image
        shell: bash

      - name: native-image
        run: $GRAALVM_HOME/native-image
        shell: bash

#  uname -mo
#      x86_64 Msys
#      - name: aa
#        run: ln -s $GRAALVM_HOME/native-image.cmd $GRAALVM_HOME/native-image
#        shell: bash
#      - name: b
#        run: $GRAALVM_HOME/bin/native-image --version
#        run: ls -lha $GRAALVM_HOME/bin
#        shell: bash
