name: GraalVM Native Image builds
on: [push, pull_request]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  image-generation:
    name: Test
    runs-on: windows-latest

    steps:
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: a
        run: java -version && uname -mo
        shell: bash
      - name: b
#        run: $GRAALVM_HOME/bin/native-image --version
        run: ls -lha $GRAALVM_HOME/bin/ --version
        shell: bash
